### ISSUE TITLE
Wrzucenie poprzedniego kodu na naszego gh

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#1]
Trzeba przejrzeć kod z poprzednich lat i uporządkować go i wrzucić w sensownej postaci do nas, jednak trzeba się zastanowić czy nie chcemy zabierać się do tego od zera

Apka z 2021 roku:
https://github.com/theATM/Vison-Project-Repository?fbclid=IwAR3HBpQuoYLtyh7VXsPHpzIIjjn8vIhWPTB4Q3-4lyreNeEyyWEbuwPnucI

**Comment by Buzeqq** [comment]
Dla aplikacji na iOS żaden kod nie zostanie ponownie wykorzystany. Będzie stworzona od zera natywna aplikacja w języku Swift.

**Comment by qaziok** [comment]
@kjedrasz2137, a jak sprawa z Androidem?

**Comment by kjedrasz2137** [comment]
@jankejc

**Comment by kjedrasz2137** [comment]
## Android
Aplikacja będzie napisana od zera w Java/Kotlin
