### ISSUE TITLE
Research i specyfikacja TalkBack w aplikacji na Androida.

### ISSUE THREAD

**Issue by jankejc** [cvlab-ai/polish_banknotes#13]
### Przegląd
Ten wątek jest przeznaczony do zbierania wszelkich ustaleń i wiedzy związanych z funkcją **TalkBack** w aplikacji na androida. Będzie ona odpowiedzialna za **głosową wiadomość zwrotną** uzyskaną z algorytmu AI odnośnie rozpoznanego banknotu. 

### Zamierzony wynik
W pełni gotowy prototyp funkcji gotowy do implementacji w etapie tworzenia aplikacji.

### Lista zadań (bieżący stan wątku)
_Lista zadań będzie w miarę możliwości odpowiadała bieżącemu etapowi pracy nad funkcją_ 
- [ ] Research związany z TalkBack.

### Lista funkcjonalności (bez kolejności)
- [ ]  _tutaj będą funkcjonalności_

### Porządek
Zanim ktoś doda kolejne zadanie albo funkcjonalność proszę dodać komentarz w wątku, przedyskutować to na DC, bądź skontaktować się ze mną bezpośrednio.

**Comment by qaziok** [comment]
Zamysł kozak jestem mocno za, ale proponuje to przenieść do sekcji Wiki, tam nic nie przepadnie, issues są bardziej na rzeczy bieżące, a nie na takie trzymanie w nieskończoność. Jak masz tą listę z funkcjonalnościami, to każdy z tych dodanych elementów nadaje się jak najbardziej na issue

**Comment by qaziok** [comment]
Plus usunąłem label android bo chciałbym żeby technologie były w swojej własnej zakładce, labele zostawmy na opisy - fakt sam dodałem tam `data`, ale stwierdziłem że to jest jednak bardziej technologia

**Comment by jankejc** [comment]
Jak najbardziej rozumiem zamysł tymczasowości issues, tylko już np. w wiki nie podlinkuje nowych issues do listy zadań, komentarzy, a tutaj mogę. Wzorowałem się na tym przykładzie. [https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists](url) Faktycznie, ten wątek pewnie by trochę wisiał. To już jak uznamy. Ja osobiście, bym pogodził się z tym, że będzie to trochę wisiało, bo dzięki temu będzie to dynamiczniejsze niż wiki, a tego myślę, że potrzebuję.

**Comment by jankejc** [comment]
Issue przeniesiony do Wiki.
