### ISSUE TITLE
Dokumentacja projektowa

### ISSUE THREAD

**Issue by jankejc** [cvlab-ai/polish_banknotes#14]
### Przegląd
Wątek będzie poświęcony wymaganej **dokumentacji**. Stworzone branche będą dawały możliwość stałego zapisywania "**logów swojej pracy**". Jest to niezbędne do późniejszego prostszego przełożenia podjętych działań na dokument. Po każdym podjętym działaniu zostawmy po sobie choćby **ślad**.

**Comment by jankejc** [comment]
Jako, że część dokumentacji będzie wspólna myślę, że stworzymy 3 branch'e. Jeden np. **main_doku**, drugi **android_doku** i trzeci **ios_doku**.  (do zatwierdzenia)

**Comment by qaziok** [comment]
Na githubie mamy włączona taką zakładkę jak Wiki, jeśli chcesz coś dłużej trzymać i dokumentować tam jest to bardzo dobre miejsce na to

**Comment by jankejc** [comment]
To by było spoko, tylko ja chciałem, żebyśmy w branchach już edytowali gotowe szablony dokumentacji, czyli tak naprawdę wypełniali szkielet. W zakładce, z tego co widzę i coś tam czytam na szybko, to raczej buduje się doku od zera. W takiej sytuacji myślę, że możemy podjąć jeden z dwóch kierunków. Albo robimy to tutaj wypełniając gotowe schematy, albo "logujemy" wszystko w wiki i ostatecznie też pewnie robimy jakiś issue, żeby to wszystko zmergować.

**Comment by qaziok** [comment]
Rozumiem zamysł, ogólnie propsy że już o dokumentacji myślisz xd, jednak osobiście nie jestem przekonany żeby to w branchach trzymać, myślę że tamat do większej dyskusji

**Comment by anton-0** [comment]
Spoko pomysł, żeby to na bieżąco dokumentować, ale bardziej bym się skłaniał ku trzymaniu tego w Wiki.

**Comment by jankejc** [comment]
Myślę, że okej. Wtedy będziemy logować swoją pracę w wiki, a potem spróbujemy to wszystko zebrać. 
=> Dokumentacja przejdzie do wiki - jest już issue, który się tym zajmuje. 
Tym samym zamykam obecny wątek.
