### ISSUE TITLE
Rozbudowa danych

### ISSUE THREAD

**Issue by kjedrasz2137** [cvlab-ai/polish_banknotes#23]
Trzeba rozbudować aktualnie istniejące dane. Najlepiej jakby każdy wrzucił parę zdjęć od razu na OneDrive'a. I jak już ktoś będzie robił filmik to niech potem nie wrzuca każdej klatki, tylko najlepiej wybierać klatki co np. 1 sekunde, żeby zdjęcia były w miarę możliwości różnorodne.

**Comment by mikolajwirkijowski97** [comment]
Rozbudowa danych o proceduralnie wygenerowane wariacje polskich banknotów z symulowanym oświetleniem za pomocą aplikacji Blender. Tła do zdjęć zostały pozyskane z datasetu imagenet i posłużyły również za rozszerzenie kategorii None

https://1drv.ms/u/s!AhyEhbACW7vWkecrERL3U684Y9U9kQ?e=xdvngx
