### ISSUE TITLE
Znalezienie, zrozumienie i spisanie wytycznych dotyczących aplikacji dla niewidomych/niedowidzących

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#25]
Jak w tytule - chyba jasne

**Comment by jankejc** [comment]
Z tego [artykułu](https://appinventiv.com/blog/design-accessibility-app-for-visually-impaired/) najważniejsze wytyczne dla naszej aplikacji to:
- dodawanie tekstu alternatywnego,
- nieopieranie się na informacjach wizualnych tj. kolory,
- minimalizm,
- warto przetestować aplikację pod kątem osoby niewidomej.

**Comment by jankejc** [comment]
Warto rozważyć [haptyczną wiadomość zwrotną](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8749676/) w naszej aplikacji. Możliwe, że może ona wspomóc androidowy TalkBack, albo chociaż pomóc w opisaniu stanu aplikacji. Z tego co czytam, to ludzie niewidomi prawdopodobnie potrafiliby zapamiętać poszczególne "wzorce haptyczne" (moja nazwa na sposoby wibracji). Takie podejście mogłoby zwiększyć satysfakcję z korzystania z danej aplikacji, gdyż myślę, że im więcej zmysłów jest zaangażowanych tym lepiej.

**Comment by jankejc** [comment]
Myślę, że też warto by rozważyć możliwe opcje w aplikacji: **czy wgl powinny być jakieś dostępne**? 
Jeśli na razie ograniczamy się tylko do polskiego nominału to może od razu po starcie udostępnić tylko widok kamery i działający algorytm? Z drugiej strony taka aplikacja nie musi być aż tak prosta. Mam na myśli dodanie jakichś opcji w przyszłości np. zmianę nominału. W takim przypadku **jak skierować** niewidomego na "trop" opcji (mam na myśli nie opieraniu się na ikonkach, ale jakaś forma przekazania informacji, że są jakieś opcje i jak się do nich dostać).

**Comment by Buzeqq** [comment]
Wytyczne dla deweloperów aplikacji iOS dotyczące dostępności: https://developer.apple.com/design/human-interface-guidelines/foundations/accessibility/
