### ISSUE TITLE
Rozpoczęcie wdrażania zaleceń dla niewidomych w aplikacji Android

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#28]

**Comment by jankejc** [comment]
Latest branch related achievement.

https://user-images.githubusercontent.com/26117679/211272349-c1ad0f22-042c-4195-9d2a-a752c76ac9bd.MOV

**Comment by jankejc** [comment]
https://user-images.githubusercontent.com/26117679/212617392-e45b3411-2f30-45fa-b9f2-170c201c5c63.MOV

Last branch related achivement.
The app is vibrating on older devices than Oreo.

**Comment by jankejc** [comment]
Potrzebuję jeszcze tylko zrobić testy i poprawki haptyki na androidzie 8.0+ i zamykam issue.
