### ISSUE TITLE
Założenie kont na serwerze ai.eti.pg.gda.pl

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#3]
Potrzebujemy założyć konta, żeby mieć dostęp do serwerów obliczeniowych i przyjemnie trenować sieci

https://cemet.eti.pg.gda.pl/course/view.php?id=2

**Comment by kjedrasz2137** [comment]
Klucz dostępu do kursu: dgx2018

**Comment by kjedrasz2137** [comment]
Po dwóm osobom z każdego teamu założono konta na ai.eti.pg.gda.pl oraz deep.eti.pg.gda.pl
