### ISSUE TITLE
Próg zakończenia rozpoznania banknotu.

### ISSUE THREAD

**Issue by jankejc** [cvlab-ai/polish_banknotes#31]
Zacząłem szukać i rozważać wytyczne co do naszych aplikacji w #25 i natrafiłem na pewną ścianę w myśleniu. Jak my korzystamy z aplikacji prototypowych to **widzimy** klasyfikację, ale dla użytkowników trzeba dać jedną odpowiedź, która będzie im przedstawiona. 

**Czy założymy pewien próg w modelu, po którym uznamy, że "to jest ten banknot"?**

**Comment by kjedrasz2137** [comment]
Gdybyśmy mieli tylko klasy '10', '20', '50', '100', '200', '500' to wtedy na pewno potrzebowalibyśmy progu (przypadek gdy na zdjęciu nie ma banknotu -> nie możemy dać w odpowiedzi klasę która ma największe probability). Jednak gdy mamy dodatkową klasę 'None' to próg traci trochę na znaczeniu, ale myślę że i tak warto go dodać. Podczas testowania aplikacji będzie można dobierać próg i sprawdzać dla którego aplikacja działa najlepiej. Pamiętajmy, że są też [inne metryki](https://towardsdatascience.com/20-popular-machine-learning-metrics-part-1-classification-regression-evaluation-metrics-1ca3e282a2ce) niż 'accuracy', np. 'precision', 'recall', 'f1 score', 'auc'. Z innej metryki skorzystamy jeśli chcemy mieć jak najwięcej poprawnych odpowiedzi a z innej jeśli jak najmniej niepoprawnych.

**Comment by jankejc** [comment]
Dobra, ciekawy temat. Odpowiedź mnie całkiem satysfakcjonuje. Dzięki!
