### ISSUE TITLE
Dostęp do najnowszych danych z banknotów

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#4]
Potrzebujemy ogarnąć najnowsze banknoty z lat 2020-2021, żeby wrzucić je do danych treningowych

**Comment by qaziok** [comment]
Możliwe, że ogarnę jakieś świeże zdjęcia banknotów, ale fajnie jakby każdy coś poszukał

**Comment by kjedrasz2137** [comment]
Można zamknąć jako duplikat tego [issue](https://github.com/cvlab-ai/polish_banknotes/issues/20). Można stworzyć nowe issue dotyczące rozbudowy aktualnie istniejących danych

**Comment by kjedrasz2137** [comment]
Ogarnięte.
