### ISSUE TITLE
Przejrzenie i uporządkowanie danych

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#5]
Trzeba przejrzeć dane jakie mamy

Dataset 2020:
https://www.kaggle.com/datasets/bartomiejgawrych/polish-banknotes-polskie-banknoty?select=README.md

Dataset 2021:
https://www.kaggle.com/datasets/99636797e98397fa6161113867b50bed663be07900885852cda713b1cc76e52d?select=info.txt

**Comment by kjedrasz2137** [comment]
Połączone powyższe datasety
OneDrive: 
https://1drv.ms/u/s!AhyEhbACW7vWjzlGZKB9Sml4ehMQ?e=P0S8ZH

**Comment by qaziok** [comment]
Połączone z #29

**Comment by StanislawSm** [comment]
Musimy jeszcze ustalić jak dokładnie ma wyglądać format tych meta danych. Czy mają być dla każdego zdjęcia czy dla klasy zbiorcze?
