### ISSUE TITLE
Wybranie środowiska dla sieci

### ISSUE THREAD

**Issue by qaziok** [cvlab-ai/polish_banknotes#6]
Trzeba wybrać w czym będziemy robić nasz sieci neuronowe, żeby było wspólne środowisko na przyszłość

**Comment by Buzeqq** [comment]
### iOS
Jeżeli chodzi o aplikacje na system iOS, to najważniejsze jest to, aby wybrana bibliotek, wspierała eksportowanie do pliku `.mlmodel` lub [ML Package](https://developer.apple.com/documentation/coreml/updating_a_model_file_to_a_model_package) . Modele tego typu wspierane są od systemu `iOS 11.0+` (iPhone 5S+), dzięki frameworkowi [Core ML](https://developer.apple.com/documentation/coreml). 

#### Core ML Tools
Dzięki narzędziu [Core ML Tools](https://coremltools.readme.io/docs) jesteśmy w stanie wykorzystać takie biblioteki jak: [TensorFlow](https://www.tensorflow.org/), [PyTorch](https://pytorch.org/), [scikit-learn](https://scikit-learn.org/stable/) i nie tylko.

![image](https://user-images.githubusercontent.com/46223928/198040380-35546a7f-5748-4d36-8c72-2aae8448cc2b.png)

**Comment by kjedrasz2137** [comment]
### Android 
Wybrane przez nas biblioteki to [TensorFlow](https://www.tensorflow.org/), [TensorFlow Lite](https://www.tensorflow.org/lite) oraz [Keras](https://keras.io/). 
TensorFlow daje łatwiejszą możliwość zdeployowania modelu niż PyTorch. Keras jest bardziej user-friendly oraz zapewnia spójniejsze i prostsze API niż TensorFlow, dlatego kod będzie napisany głównie w nim. Przy pomocy TensorFlow Lite nasz model będzie eksportowany do pliku z rozszerzeniem `.tflite`. Do [konwersji pomiędzy różnymi formatami](https://towardsdatascience.com/onnx-preventing-framework-lock-in-9a798fb34c92) możemy użyć [ONNX ](https://onnx.ai/)(Open Neural Network Exchange). 

![image](https://miro.medium.com/max/4800/1*3N6uPaLNEYDjtWBW1vdNoQ.webp)
